//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_Patient
    {
        public int Lab_Id { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public Nullable<System.DateTime> Test_Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Billing_Status { get; set; }
        public Nullable<int> Test_Id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Lab_Information Lab_Information { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
