//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Info
    {
        public int Room_no { get; set; }
        public Nullable<short> Room_Status { get; set; }
    
        public virtual Room_Data Room_Data { get; set; }
    }
}
